---
# This task installs and enables apache on webservers
- name: ensure apache is installed
  apt: name=apache2 update_cache=yes state=latest
- name: ensure apache is running
  service: name=apache2 state=running enabled=yes
- name: copy files to document root
  copy: src=terraform.png dest=/var/www/html/terraform.png
- name: copy application code to document root
  template: src=index.html.j2 dest=/var/www/html/index.html
  notify: restart apache
